# Use root/example as user/password credentials
version: '3.1'

services:
 establishment-ms:
    ports:
      - "8080:8080"  # Mapeando porta do host para o contÃªiner
    networks:
      - comandapay-net
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://200.98.80.143:3459/comandapp

volumes:
  postgres_data:

networks:
  comandapay-net:
