# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    volumes:
      - establishment_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: myroot
      MYSQL_DATABASE: establishment

volumes:
    establishment_db: