spring:
  profiles:
    active: test
api:
  security:
    token:
      secret: drtcwcfvugefut78ko6728yhunjdw8po807
  credentials:
    client_id: Client_Id_e3c50f7c2146dc9318dbca38d6aec71d1da6fde7
    client_secret: Client_Secret_dbc6b397dedca80d95366524b740e3ba42e6cad4
    certificate: ./certs/hom-app-comanda.p12
    sandbox: true
    debug: false

spring-doc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080


aws:
  access_key_id: AKIAT4J25ILD5XNVQJVP
  secret_access_key: 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
  s3:
    bucket: appcomanda
    region: sa-east-1

efi:
  pixKey: 9392925e-0257-417a-a180-506379529a2f
  cob:
    url: http://172.18.0.1:8082
asaas:
  api:
    url: https://api-sandbox.asaas.com
    payments: /v3/payments
    path: /v3/customers
    qrCode: /{id}/pixQrCode
    token: $aact_MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjQ3OWE0Y2U4LWFhY2UtNGQxNi1hM2EzLTliMDkyYzIyZDg5MTo6JGFhY2hfZjBjMzk0OTktZDJjMC00ODBhLWE1ZmUtODFiMDY4Yjg4ZGM0